Repository kammon10/Sustain, pull requests merged in 2022-02, with the labels that each got.

#3 Test/user
  package-lock.json
  pull_request_template.md
  src/classes/User.js
  src/classes/UserRepository.js
  test/User-test.js
  test/UserRepository-test.js
Labels: test

#4 Test/user repository
  test/User-test.js
  test/UserRepository-test.js
Labels: test

#7 Feature/fetch calls
  src/apiCalls.js
  src/scripts.js
Labels: enhancement

#13 Feature/hydration
  dist/index.html
  src/apiCalls.js
  src/classes/HydrationLog.js
  src/classes/User.js
  src/classes/UserRepository.js
  src/data/users.js
  src/scripts.js
Labels: enhancement

#14 Feature/sleep
  dist/index.html
  src/apiCalls.js
  src/classes/SleepLog.js
  src/classes/User.js
  src/classes/UserRepository.js
  src/scripts.js
Labels: enhancement

#26 Refactor UserRepository Test file
  test/UserRepository-test.js
Labels: help wanted

#27 Refactor/round 2
  dist/index.html
  src/apiCalls.js
  src/classes/HydrationLog.js
  src/classes/SleepLog.js
  src/classes/User.js
  src/classes/UserRepository.js
  src/css/styles.css
  src/scripts.js
  test/HydrationLog-test.js
  test/User-test.js
  test/sleepLog-test.js
Labels: help wanted

#44 Refactor/local server
  src/apiCalls.js
Labels: enhancement
